### ISSUE TITLE
Invalid helper name with Power Select - `dd.trigger` is not a valid name

### ISSUE THREAD

**Issue by stevetyler** [rwjblue/ember-template-lint#235] opened 2017-06-29 12:02 UTC
I've just installed the addon and fixed a lot of issues but I keep getting this error with Power Select and not sure how to resolve it? Thanks for any advice

`undefined: `dd.trigger` is not a valid name for a helper on line 50. (collated-client/components/view-widget/template): 
`Error: `dd.trigger` is not a valid name for a helper on line 50.
    at SyntaxError.Error (native)
    at new SyntaxError (/Users/apple/Projects/collated-client/node_modules/@glimmer/syntax/dist/commonjs/es5/lib/errors/syntax-error.js:14:27)
    at assertIsSimplePath (/Users/apple/Projects/collated-client/node_modules/@glimmer/compiler/dist/commonjs/es5/lib/template-compiler.js:476:15)
    at TemplateCompiler.prepareHelper (/Users/apple/Projects/collated-client/node_modules/@glimmer/compiler/dist/commonjs/es5/lib/template-compiler.js:342:9)
    at TemplateCompiler.block (/Users/apple/Projects/collated-client/node_modules/@glimmer/compiler/dist/commonjs/es5/lib/template-compiler.js:196:14)
    at /Users/apple/Projects/collated-client/node_modules/@glimmer/compiler/dist/commonjs/es5/lib/template-compiler.js:71:25
    at Array.forEach (native)
    at TemplateCompiler.process (/Users/apple/Projects/collated-client/node_modules/@glimmer/compiler/dist/commonjs/es5/lib/template-compiler.js:64:17)
    at Function.compile (/Users/apple/Projects/collated-client/node_modules/@glimmer/compiler/dist/commonjs/es5/lib/template-compiler.js:57:32)
    at precompile (/Users/apple/Projects/collated-client/node_modules/@glimmer/compiler/dist/commonjs/es5/lib/compiler.js:45:60)`
`

**Comment by rwjblue** [comment] 2017-06-29 13:30
Yeah, there is currently an issue with how we parse this scenario. 

Closing as a duplicate of https://github.com/rwjblue/ember-template-lint/issues/230. Hopefully I can find time today to look at it...

**Closed** 2017-06-29 13:30 UTC

**Comment by stevetyler** [comment] 2017-06-30 08:42
Thanks Robert, sorry for the duplicate.
