### ISSUE TITLE
Update Usage in docs

### ISSUE THREAD

**Issue by Dejavs** [rwjblue/ember-template-lint#151] opened 2016-12-10 22:58 UTC
I'm doing custom linter task which works without ember-cli, so in my case i just need ember-template-lint package. It's important for me beacuse in our Continous Integration process lints are checked before whole node-modules are installed and before ember app is built (for lint process we're using separate package.json definition which includes only packages for lints, that's CI performance optimization).

I've noticed that code in Usage section is invalid.
```js
var TemplateLinter = require('ember-template-lint');

var linter = new TemplateLinter();
var template = fs.readFileSync('some/path/to/template.hbs', { encoding: 'utf8' });
var results = linter.verify(template);
```

That's because `verify` function doesn't accept template string, it expects object with 2 params: `source` and `moduleId`. So above code should looks like:
```js
var TemplateLinter = require('ember-template-lint');

var linter = new TemplateLinter();
var templatePath = 'some/path/to/template.hbs';
var template = fs.readFileSync(templatePath, { encoding: 'utf8' });
var results = linter.verify({ source: template, moduleId: templatePath });
```

**Comment by Dejavs** [comment] 2016-12-11 00:01
If somebody is interested, thats my code for linter task using only ember-template-lint plugin, which works similar to cli version. Could be useful if somebody would like to separate lints from tests (eg. for better CI pipelines readability):
```js
const fs = require('fs');
const walker = require('walker');
const path = require('path');
const TemplateLinter = require('ember-template-lint');
const linter = new TemplateLinter();

const templatesPath = 'app/templates/';
const errors = [];

walker(templatesPath).on('file', (filePath) => {
  if (path.extname(filePath) === '.hbs') {
    const moduleId = path.relative(templatesPath, filePath);
    const source = fs.readFileSync(filePath, { encoding: 'utf8' });
    const result = linter.verify({
      moduleId,
      source
    });
    if (result.length > 0) {
      errors.push(...result);
    }
  }
}).on('end', () => {
  if (errors.length === 0) {
    return;
  }
  errors.forEach((error, index) => {
    console.log(`#${index+1}`, `${error.rule}:`, error.message);
    console.log(`(${error.moduleId} @ L${error.line}:C${error.column}):`);
    console.log(error.source);
    if(error.fix) {
      console.log('(FIX):');
      console.log(error.fix.text);
    }
    console.log();
  });
  console.log(`===== ${errors.length} Template Linting Errors`);
  process.exit(1);
});
```

**Comment by Dejavs** [comment] 2016-12-11 22:47
I've released light version of ember-cli-templates which could be useful if somebody needs just fast linting in Continous Integration lint step, based on above code.
https://www.npmjs.com/package/ember-cli-light-template-lint

**Comment by rwjblue** [comment] 2016-12-11 23:14
Seems kinda odd to release this instead of trying to land it here, but thanks for your interest. 

This issue is a duplicate of https://github.com/rwjblue/ember-template-lint/issues/108 and an official baked in solution is being worked on in https://github.com/rwjblue/ember-template-lint/pull/152. 

Hope to have something landed in a few days. Closing this as a duplicate though.

**Closed by rwjblue** 2016-12-11 23:14 UTC

**Comment by Dejavs** [comment] 2016-12-12 00:05
I aggree with your opinion. I'll deprecate my plugin after it'll be possible to run ember-template-lint from CLI. I can try to make PR here with CLI functionality.
